# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>
CodeOfConductContact: jeffrey.sarnoff@gmail.com
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.11'
License: MIT
LicenseCopyrightHolders: Jeffrey Sarnoff
MarkdownIndentation: 2
PackageName: FasterFloatsL
PackageOwner: JeffreySarnoff
PackageUUID: f49cccef-7284-4a17-96a5-4978803b0672
_commit: v0.15.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
